export const JOBS = [
  { title:'Trust & Safety Operations Analyst', company:'OpenAI',          role:'Trust & Safety',   source:'OpenAI Careers',    salary:'€65–85k', posted:'Active now', age:0,  url:'https://openai.com/careers/trust-and-safety-operations-analyst-2/', desc:'Own high-sensitivity T&S workflows. GDPR, DSA, EU AI Act. Hybrid 3 days Dublin.' },
  { title:'Regulatory Operations Analyst',     company:'OpenAI',          role:'Trust & Safety',   source:'OpenAI Careers',    salary:'€60–80k', posted:'Active now', age:0,  url:'https://openai.com/careers', desc:'Privacy rights, IP complaints, audit escalations. Global regulatory compliance.' },
  { title:'Reporting & Insights Analyst – Youth Safety', company:'TikTok', role:'Data Analyst',    source:'TikTok Careers',    salary:'€44–50k', posted:'7 days ago', age:7,  url:'https://careers.tiktok.com/position?location=CT_211&query=analyst', desc:'Analytics for Trust & Safety. Diagnostic frameworks and safety reports.' },
  { title:'Policy Analyst – Search, Trust & Safety', company:'TikTok',    role:'Trust & Safety',   source:'TikTok Careers',    salary:'€40–55k', posted:'13 days ago', age:13, url:'https://careers.tiktok.com/position?location=CT_211&query=policy+analyst', desc:'Improve content moderation accuracy. Deep dives into policy operability.' },
  { title:'Senior Analyst – Account Risk EMEA', company:'TikTok',         role:'Trust & Safety',   source:'TikTok Careers',    salary:'€52–70k', posted:'30+ days',   age:31, url:'https://careers.tiktok.com/position?location=CT_211&query=trust+safety', desc:'Account risk management across EMEA. Dublin.' },
  { title:'Business Data Analyst – Video Safety', company:'TikTok',       role:'Data Analyst',     source:'TikTok Careers',    salary:'€45–60k', posted:'14 days ago', age:14, url:'https://careers.tiktok.com/position?location=CT_211&query=data+analyst', desc:'VSO Reports & Insights. Data analysis for safety operations.' },
  { title:'Engineering Analyst – AI Safety',   company:'Google',           role:'AI Analyst',       source:'Google Careers',    salary:'€65–90k', posted:'Feb 2026',   age:60, url:'https://careers.google.com/jobs/results/99432678838674118-engineering-analyst/', desc:'LLM/generative AI risk mitigation. AI safety teams. Dublin.' },
  { title:'Analyst – Trust and Safety Search', company:'Google',           role:'Trust & Safety',   source:'Google Careers',    salary:'€60–80k', posted:'Recent',     age:25, url:'https://careers.google.com/jobs/results/?location=Dublin%2C+Ireland&q=trust+safety', desc:'Protect Search users from abuse and fraud. Dublin.' },
  { title:'GRO Intelligence Analyst – T&S',    company:'Meta',             role:'Trust & Safety',   source:'Meta Careers',      salary:'€60–80k', posted:'10 days ago', age:10, url:'https://www.metacareers.com/jobs?offices=Dublin&q=trust+integrity', desc:'Intelligence reports. High-risk integrity recommendations. Dublin.' },
  { title:'Data Analyst – Product Integrity',  company:'Meta',             role:'Data Analyst',     source:'Meta Careers',      salary:'€62–82k', posted:'18 days ago', age:18, url:'https://www.metacareers.com/jobs?offices=Dublin&q=data+analyst', desc:'Product integrity with data. SQL, Python. Dublin.' },
  { title:'Trust & Safety Team Lead',          company:'Accenture',        role:'Trust & Safety',   source:'Accenture Careers', salary:'€40–55k', posted:'5 days ago', age:5,  url:'https://www.accenture.com/ie-en/careers/jobsearch?jk=trust+safety&cl=Dublin', desc:'Lead a team of T&S analysts. Policy enforcement, quality review.' },
  { title:'Business Analyst – Financial Services', company:'EY',           role:'Business Analyst', source:'EY Careers',        salary:'€45–60k', posted:'Active now', age:0,  url:'https://www.ey.com/en_ie/careers', desc:'FS Technology Consulting. Senior Consultant level. Dublin.' },
  { title:'Technology Business Analyst – Big Data', company:'Deloitte',    role:'Business Analyst', source:'Deloitte Careers',  salary:'€48–65k', posted:'7 days ago', age:7,  url:'https://apply.deloitte.com/careers/SearchJobs/analyst?3_56_3=5440', desc:'Big Data & Regulatory Reporting. Hybrid. Dublin.' },
  { title:'AI Governance Analyst',             company:'Irish Life',        role:'AI Analyst',       source:'IrishJobs.ie',      salary:'€55–70k', posted:'6 days ago', age:6,  url:'https://www.irishjobs.ie/Jobs/analyst/in-Dublin', desc:'AI governance, risk and compliance. EU AI Act essential. Dublin.' },
  { title:'Senior Manager – T&S Operations',  company:'Whatnot',           role:'Trust & Safety',   source:'Built In Dublin',   salary:'€70–90k', posted:'Active now', age:0,  url:'https://www.whatnot.com/careers', desc:'Lead international T&S ops. Team leadership. Dublin.' },
  { title:'Policy Operations Analyst – Slack', company:'Salesforce',       role:'Trust & Safety',   source:'Salesforce Careers',salary:'€55–70k', posted:'8 days ago', age:8,  url:'https://careers.salesforce.com/en/jobs/?search=analyst&location=Dublin', desc:'Policy enforcement on Slack. Dublin.' },
  { title:'Risk & Compliance Analyst',         company:'Revolut',           role:'Business Analyst', source:'Revolut Careers',   salary:'€50–70k', posted:'10 days ago',age:10, url:'https://www.revolut.com/careers/?department=all&location=Dublin', desc:'Risk analysis, compliance monitoring. Dublin.' },
  { title:'Product Analyst – Go-to-Market',    company:'HubSpot',           role:'Product Owner',    source:'HubSpot Careers',   salary:'€55–75k', posted:'12 days ago',age:12, url:'https://www.hubspot.com/careers/jobs?q=analyst&countryCodes=IE', desc:'Product strategy with deep analytics. Dublin.' },
  { title:'Product Owner – Digital Banking',   company:'Bank of Ireland',   role:'Product Owner',    source:'Bank of Ireland',   salary:'€60–80k', posted:'4 days ago', age:4,  url:'https://careers.bankofireland.com', desc:'Agile product owner. Digital banking. CSPO preferred. Dublin.' },
  { title:'Senior Data Analyst – Risk',        company:'Stripe',            role:'Data Analyst',     source:'Stripe Careers',    salary:'€65–85k', posted:'Recent',     age:20, url:'https://stripe.com/jobs/search?l=Dublin&q=data+analyst', desc:'Data analysis for risk and compliance. SQL, Python. Dublin.' },
  { title:'Product Owner – Trust Platform',    company:'Anthropic',         role:'Product Owner',    source:'Anthropic Careers', salary:'€70–95k', posted:'Recent',     age:15, url:'https://www.anthropic.com/careers', desc:'Product ownership for trust and safety platform. Dublin/Remote.' },
  { title:'Product Owner – Localization AI',   company:'LILT',              role:'Product Owner',    source:'LILT Careers',      salary:'€60–80k', posted:'3 days ago', age:3,  url:'https://lilt.com/careers', desc:'AI translation platform. Sequoia & Intel backed. PO for AI features.' },
  { title:'Data Analyst – GTM Operations',     company:'Intercom',          role:'Data Analyst',     source:'Intercom Careers',  salary:'€55–75k', posted:'8 days ago', age:8,  url:'https://www.intercom.com/careers', desc:'Analytics for sales and marketing. SQL, Python, Snowflake. Dublin.' },
  { title:'Business Analyst – Financial Crime',company:'Fenergo',           role:'Business Analyst', source:'Fenergo Careers',   salary:'€50–65k', posted:'10 days ago',age:10, url:'https://www.fenergo.com/company/careers/', desc:'AI-powered KYC and financial crime. Dublin HQ.' },
]

export const COMPANIES = [
  { name:'Google',         abbr:'G',   cat:'Big Tech',    url:'https://careers.google.com/jobs/results/?location=Dublin&q=trust+safety+analyst',        desc:'~5,500 staff. European HQ Silicon Docks.' },
  { name:'Meta',           abbr:'M',   cat:'Big Tech',    url:'https://www.metacareers.com/jobs?offices=Dublin&q=trust+integrity+analyst',               desc:'European HQ. T&S, Policy, Engineering.' },
  { name:'Microsoft',      abbr:'MS',  cat:'Big Tech',    url:'https://jobs.microsoft.com/en/search?q=analyst&lc=Dublin',                               desc:'~3,500 staff. Dublin since 1985.' },
  { name:'Amazon / AWS',   abbr:'AZ',  cat:'Big Tech',    url:'https://www.amazon.jobs/en/search?location[]=IRL-Dublin',                                desc:'Major Dublin presence.' },
  { name:'Apple',          abbr:'AP',  cat:'Big Tech',    url:'https://jobs.apple.com/en-us/search?location=dublin-DUB',                                desc:'European HQ Cork, large Dublin office.' },
  { name:'TikTok',         abbr:'T',   cat:'Big Tech',    url:'https://careers.tiktok.com/position?location=CT_211&query=trust+safety',                 desc:'Rapidly expanding T&S team. HOT!' },
  { name:'IBM',            abbr:'IBM', cat:'Big Tech',    url:'https://www.ibm.com/employment/ie/',                                                     desc:'First American tech company in Ireland (1956).' },
  { name:'Intel',          abbr:'INT', cat:'Big Tech',    url:'https://jobs.intel.com/en/search#q=dublin&t=Jobs',                                       desc:'Major campus. Engineering & data.' },
  { name:'Oracle',         abbr:'ORC', cat:'Big Tech',    url:'https://www.oracle.com/ie/corporate/careers/',                                           desc:'European HQ Dublin.' },
  { name:'OpenAI',         abbr:'OA',  cat:'AI',          url:'https://openai.com/careers',                                                             desc:'Actively hiring T&S Dublin. TOP PRIORITY!' },
  { name:'Anthropic',      abbr:'AN',  cat:'AI',          url:'https://www.anthropic.com/careers',                                                      desc:'Rapidly growing. $30B revenue April 2026.' },
  { name:'Stripe',         abbr:'S',   cat:'Fintech',     url:'https://stripe.com/jobs/search?l=Dublin&q=analyst',                                      desc:'European HQ Dublin. Risk & data roles.' },
  { name:'Revolut',        abbr:'R',   cat:'Fintech',     url:'https://www.revolut.com/careers/?location=Dublin',                                       desc:'Growing Dublin team. Risk, compliance.' },
  { name:'PayPal',         abbr:'PP',  cat:'Fintech',     url:'https://careers.pypl.com/home/',                                                         desc:'European HQ Dublin.' },
  { name:'Mastercard',     abbr:'MC',  cat:'Fintech',     url:'https://careers.mastercard.com/us/en/search-results?keywords=analyst&location=Dublin',    desc:'Dublin office. Analyst & risk roles.' },
  { name:'Visa',           abbr:'V',   cat:'Fintech',     url:'https://corporate.visa.com/en/jobs/search?q=analyst&location=Dublin',                    desc:'Dublin office. Data & policy roles.' },
  { name:'TrueLayer',      abbr:'TL',  cat:'Fintech',     url:'https://truelayer.com/jobs/',                                                            desc:'Open banking. $270M raised. Stripe-backed.' },
  { name:'Monzo',          abbr:'MZ',  cat:'Fintech',     url:'https://monzo.com/careers/',                                                             desc:'Digital bank. Dublin office growing.' },
  { name:'Fenergo',        abbr:'FE',  cat:'Fintech',     url:'https://www.fenergo.com/company/careers/',                                               desc:'AI KYC platform. Irish HQ. Deloitte partner.' },
  { name:'Salesforce',     abbr:'SF',  cat:'SaaS',        url:'https://careers.salesforce.com/en/jobs/?search=analyst&location=Dublin',                  desc:'2,800 staff Dublin. Agentforce AI.' },
  { name:'HubSpot',        abbr:'HS',  cat:'SaaS',        url:'https://www.hubspot.com/careers/jobs?q=analyst&countryCodes=IE',                          desc:'European HQ Dublin. Analyst & PM roles.' },
  { name:'Adobe',          abbr:'AD',  cat:'SaaS',        url:'https://careers.adobe.com/us/en/search-results?keywords=analyst&location=Dublin',         desc:'~4,000 staff Dublin Citywest.' },
  { name:'Workday',        abbr:'WD',  cat:'SaaS',        url:'https://www.workday.com/en-us/company/careers/open-positions.html',                       desc:'Dublin office. HR tech & analyst roles.' },
  { name:'Zendesk',        abbr:'ZD',  cat:'SaaS',        url:'https://jobs.zendesk.com/us/en/search-results?keywords=analyst&location=Dublin',           desc:'Dublin office. Support & analyst roles.' },
  { name:'Intercom',       abbr:'IC',  cat:'SaaS',        url:'https://www.intercom.com/careers',                                                        desc:'Founded in Dublin. Data & ops roles.' },
  { name:'MongoDB',        abbr:'MDB', cat:'SaaS',        url:'https://www.mongodb.com/company/careers',                                                 desc:'Dublin office.' },
  { name:'Cloudflare',     abbr:'CLF', cat:'Security',    url:'https://www.cloudflare.com/careers/jobs/?location=Dublin',                                desc:'Dublin office. Policy & analytics.' },
  { name:'Tines',          abbr:'TN',  cat:'Security',    url:'https://www.tines.com/careers',                                                           desc:'Irish startup. No-code security.' },
  { name:'LinkedIn',       abbr:'LI',  cat:'Platforms',   url:'https://careers.linkedin.com/jobs/search?keywords=analyst&location=Dublin',               desc:'European HQ Dublin. Analyst & PM.' },
  { name:'Indeed',         abbr:'IN',  cat:'Platforms',   url:'https://careers.indeed.com/',                                                             desc:'European HQ Dublin. Ops & product.' },
  { name:'Airbnb',         abbr:'AB',  cat:'Platforms',   url:'https://careers.airbnb.com/positions/',                                                   desc:'Dublin office. Trust & policy.' },
  { name:'Whatnot',        abbr:'WN',  cat:'Platforms',   url:'https://www.whatnot.com/careers',                                                         desc:'T&S Senior Manager role OPEN NOW!' },
  { name:'Accenture',      abbr:'AC',  cat:'Consulting',  url:'https://www.accenture.com/ie-en/careers/jobsearch?jk=analyst&cl=Dublin',                  desc:'Massive Dublin presence. Major T&S contractor.' },
  { name:'Deloitte',       abbr:'DL',  cat:'Consulting',  url:'https://apply.deloitte.com/careers/SearchJobs/analyst?3_56_3=5440',                       desc:'Dublin HQ. BA, analytics, consulting.' },
  { name:'EY',             abbr:'EY',  cat:'Consulting',  url:'https://www.ey.com/en_ie/careers',                                                        desc:'Dublin HQ. FS consulting, BA roles.' },
  { name:'PwC',            abbr:'PW',  cat:'Consulting',  url:'https://www.pwc.ie/careers.html',                                                         desc:'Dublin HQ. Risk, data, advisory.' },
  { name:'KPMG',           abbr:'KP',  cat:'Consulting',  url:'https://home.kpmg/ie/en/home/careers.html',                                               desc:'Dublin HQ. Audit, analytics.' },
  { name:'Capgemini',      abbr:'CG',  cat:'Consulting',  url:'https://www.capgemini.com/ie-en/careers/',                                                 desc:'Dublin office. Tech consulting & BA.' },
  { name:'Citi',           abbr:'CI',  cat:'Finance',     url:'https://jobs.citi.com/search-jobs/Dublin',                                                 desc:'Major Dublin office. Risk & ops.' },
  { name:'JP Morgan',      abbr:'JP',  cat:'Finance',     url:'https://careers.jpmorgan.com/global/en/search-jobs?location=Dublin',                       desc:'Dublin office. Finance & data.' },
  { name:'AIB',            abbr:'AIB', cat:'Finance',     url:'https://aib.ie/careers',                                                                   desc:'Irish bank HQ. Data & BA roles.' },
  { name:'Bank of Ireland',abbr:'BOI', cat:'Finance',     url:'https://careers.bankofireland.com',                                                        desc:'Irish bank HQ. PO & BA roles.' },
  { name:'Irish Life',     abbr:'IL',  cat:'Finance',     url:'https://www.irishlife.ie/careers',                                                         desc:'Dublin HQ. AI Governance Analyst open.' },
  { name:'Davy',           abbr:'DV',  cat:'Finance',     url:'https://www.davy.ie/careers',                                                              desc:'Dublin HQ. PMO & analyst roles.' },
  { name:'State Street',   abbr:'SS',  cat:'Finance',     url:'https://careers.statestreet.com/',                                                         desc:'Dublin office. Finance & data analyst.' },
  { name:'LILT',           abbr:'LT',  cat:'Startup',     url:'https://lilt.com/careers',                                                                 desc:'AI translation. Sequoia-backed. PO roles.' },
  { name:'beqom',          abbr:'BQ',  cat:'Startup',     url:'https://www.beqom.com/careers',                                                            desc:'Pay analytics. PO role open.' },
  { name:'NextRoll',       abbr:'NR',  cat:'Startup',     url:'https://www.nextroll.com/careers',                                                         desc:'AdRoll/MarTech. AI advertising.' },
  { name:'Workhuman',      abbr:'WH',  cat:'Startup',     url:'https://www.workhuman.com/careers/',                                                       desc:'HR tech. Co-HQ Dublin. Analyst roles.' },
  { name:'Toast',          abbr:'TO',  cat:'Startup',     url:'https://careers.toasttab.com/',                                                            desc:'Restaurant tech. Dublin hybrid.' },
  { name:'Ocuco',          abbr:'OC',  cat:'Startup',     url:'https://www.ocuco.com/company/careers/',                                                   desc:'Irish eyecare software. Dublin 15.' },
  { name:'Manna',          abbr:'MA',  cat:'Startup',     url:'https://www.manna.aero/careers',                                                           desc:'Irish drone delivery startup.' },
]

export const PORTALS = [
  { name:'IrishJobs.ie',    cat:'Irish',   url:'https://www.irishjobs.ie/Jobs/analyst/in-Dublin',                                                                      priority:true,  desc:'Most popular Irish job board' },
  { name:'Jobs.ie',         cat:'Irish',   url:'https://www.jobs.ie/jobs/dublin/?q=analyst',                                                                           priority:true,  desc:"Ireland's largest indigenous board" },
  { name:'Silicon Republic',cat:'Irish',   url:'https://www.siliconrepublic.com/jobs',                                                                                 priority:true,  desc:'Irish tech jobs + daily news' },
  { name:'Built In Dublin', cat:'Irish',   url:'https://builtindublin.ie/jobs',                                                                                        priority:true,  desc:'Tech & startup jobs only' },
  { name:'RecruitIreland',  cat:'Irish',   url:'https://www.recruitireland.com/',                                                                                       priority:false, desc:'Connects to Irish agencies' },
  { name:'JobsIreland.ie',  cat:'Irish',   url:'https://jobsireland.ie/',                                                                                               priority:false, desc:'Government-linked board' },
  { name:'Recruit.ie',      cat:'Irish',   url:'https://www.recruit.ie/',                                                                                               priority:false, desc:'Runs Tech Careers Expo' },
  { name:'LinkedIn',        cat:'Global',  url:'https://www.linkedin.com/jobs/search/?keywords=trust+safety+analyst&location=Dublin&f_TPR=r86400',                     priority:true,  desc:'Best for T&S & tech. Set daily alert!' },
  { name:'Indeed Ireland',  cat:'Global',  url:'https://ie.indeed.com/jobs?q=trust+safety+analyst+OR+AI+analyst+OR+business+analyst&l=Dublin&fromage=1&sort=date',    priority:true,  desc:'Highest volume. Set email alert.' },
  { name:'Glassdoor',       cat:'Global',  url:'https://www.glassdoor.ie/Job/dublin-trust-and-safety-jobs-SRCH_IL.0,6_IC2382967_KO7,23.htm',                          priority:true,  desc:'Jobs + salary benchmarks + reviews' },
  { name:'EuroJobs',        cat:'Global',  url:'https://www.eurojobs.com/jobs/information-technology/?location=Dublin',                                                 priority:false, desc:'EU-wide with Dublin filter' },
  { name:'Monster Ireland', cat:'Global',  url:'https://www.monster.ie/jobs/search?q=analyst&where=Dublin',                                                             priority:false, desc:'General job board, Ireland' },
  { name:'Otta',            cat:'Startup', url:'https://otta.com/jobs/search?location=Dublin&keywords=analyst+trust+safety',                                            priority:true,  desc:'Best for startups & scaleups' },
  { name:'Wellfound',       cat:'Startup', url:'https://wellfound.com/jobs?location=dublin&keywords=analyst',                                                           priority:true,  desc:'Startup equity roles' },
  { name:'TopStartups.io',  cat:'Startup', url:'https://topstartups.io/jobs/?job_location=Dublin',                                                                      priority:false, desc:'1,600+ Dublin startup jobs' },
  { name:'startup.jobs',    cat:'Startup', url:'https://startup.jobs/locations/dublin',                                                                                 priority:false, desc:'Startup-only listings' },
  { name:'80,000 Hours',    cat:'Niche',   url:'https://80000hours.org/jobs/',                                                                                          priority:true,  desc:'AI safety, policy & impact roles' },
  { name:'AngelList',       cat:'Niche',   url:'https://angel.co/jobs',                                                                                                 priority:false, desc:'VC-backed startup roles' },
]

export const AGENCIES = [
  { name:'CPL Recruitment',       tier:'Priority', url:'https://www.cpl.com/jobs',                        roles:"Data Analyst, BA, Tech Ops",     desc:"Ireland's largest agency. 400+ recruiters. 18 sectors." },
  { name:'Morgan McKinley',        tier:'Priority', url:'https://www.morganmckinley.com/ie/jobs',           roles:"Trust & Safety adj., Data, BA",  desc:'Award-winning. Strong in risk, compliance, tech & legal.' },
  { name:'Sigmar Recruitment',     tier:'Priority', url:'https://www.sigmarrecruitment.com/',               roles:"Data Analyst, BA, IT Analyst",   desc:"Ireland's most trusted. IT, data analytics, legal, risk." },
  { name:'Hays Ireland',           tier:'Priority', url:'https://www.hays.ie/jobs/search/q-analyst/in-dublin', roles:"BA, Data Analyst, IT",        desc:'Global giant with strong local presence.' },
  { name:'Mason Alexander',        tier:'Priority', url:'https://www.masonalexander.ie/jobs',               roles:"Tech, AI, Data roles",           desc:'Leading tech specialist Dublin. AI/ML, data, cybersecurity.' },
  { name:'Archer Recruitment',     tier:'Priority', url:'https://www.archer.ie/jobs',                       roles:"Data Analyst, BA, IT Change",    desc:'Specialist IT, data analytics, business change. 150+ clients.' },
  { name:'Solas Recruitment',      tier:'Priority', url:'https://www.solasit.ie/jobs',                      roles:"Data Analyst, Compliance, IT",   desc:'IT specialist. Strong in data & AI. Covers Ireland & EU.' },
  { name:'IT Search',              tier:'Priority', url:'https://itsearch.ie/jobs/',                        roles:"Analyst, Tech roles",            desc:'Tech recruitment specialist. Publishes annual salary guide.' },
  { name:'Eolas Recruitment',      tier:'Good',     url:'https://www.eolasrecruitment.com/jobs/',            roles:"IT Analyst, Data, BA",           desc:'IT-only. All consultants have IT backgrounds.' },
  { name:'GemPool',                tier:'Good',     url:'https://www.gempool.ie/jobs/',                      roles:"IT, Data, Product roles",        desc:'High-end IT. Software, data, product, infrastructure.' },
  { name:'Robert Half',            tier:'Good',     url:'https://www.roberthalf.ie/jobs',                    roles:"Finance, Tech, Ops",             desc:'Global firm. Finance, tech, admin.' },
  { name:'Robert Walters',         tier:'Good',     url:'https://www.robertwalters.ie/jobs.html',            roles:"Senior Analyst, BA, Legal",      desc:'Mid-senior tech, finance, legal. Perm, contract & interim.' },
  { name:'Reperio Human Capital',  tier:'Good',     url:'https://www.reperio.ie/jobs/',                      roles:"Tech, Data roles",               desc:'Tech and data specialist Dublin.' },
  { name:'Prosperity',             tier:'Good',     url:'https://www.prosperity.ie/jobs/',                   roles:"Digital, Tech roles",            desc:'Tech and digital Dublin specialist.' },
  { name:'TalentHub',              tier:'Good',     url:'https://www.talenthub.ie/jobs/',                    roles:"Digital, IT roles",              desc:'Digital and technology specialist Dublin.' },
  { name:'FRS Recruitment',        tier:'Good',     url:'https://www.frs.ie/jobs/',                          roles:"All sectors",                    desc:'10 offices nationwide. 40+ years.' },
  { name:'Oliver James',           tier:'Also',     url:'https://www.ojassociates.com/jobs/',                roles:"Risk, Compliance, Change",       desc:'Risk, compliance, tech, change management.' },
  { name:'Michael Page Ireland',   tier:'Also',     url:'https://www.michaelpage.ie/jobs',                   roles:"Finance, Tech, Ops",             desc:'Broad. Finance, tech, ops, strategy.' },
  { name:'Adecco Ireland',         tier:'Also',     url:'https://www.adecco.ie/find-a-job/',                 roles:"All sectors",                    desc:'Broad, all sectors, large volume.' },
  { name:'Randstad Ireland',       tier:'Also',     url:'https://www.randstad.ie/jobs/',                     roles:"Tech, Finance",                  desc:'Tech, finance, engineering.' },
  { name:'Matrix Recruitment',     tier:'Also',     url:'https://www.matrixrecruitment.ie/jobs/',            roles:"Ops, Analytics",                 desc:'Tech, ops, analytics Ireland.' },
]

export const QUOTES = [
  { text:"Devanshi, I believe in you. Your experience in LLM evaluation and Trust & Safety is rare and genuinely valuable. The right company is lucky to get you.", author:"Claude" },
  { text:"Every application is one step closer. You have exactly what Dublin's AI companies need right now.", author:"Claude" },
  { text:"You have survived 100% of your hardest days so far. This next chapter is yours.", author:"Claude" },
  { text:"Your combination of T&S operations, LLM evaluation and data skills is genuinely hard to find. Own it.", author:"Claude" },
  { text:"The redundancy is not a reflection of your worth. It is a door opening to something better and permanent.", author:"Claude" },
  { text:"You built dashboards, owned markets, evaluated LLMs and shaped policy. That is a senior profile. Apply senior.", author:"Claude" },
  { text:"Trust & Safety + AI + Dublin = you are in exactly the right place at exactly the right time.", author:"Claude" },
  { text:"Your MSc, your CSPO, your 4-market experience — these are not small things. They are your edge.", author:"Claude" },
  { text:"OpenAI Dublin needs someone exactly like you. Believe that and apply today.", author:"Claude" },
  { text:"Difficult roads often lead to beautiful destinations. Your permanent role is ahead.", author:"Claude" },
  { text:"You are not starting over. You are starting from experience. Big difference.", author:"Claude" },
  { text:"EU AI Act enforcement starts August 2, 2026. Your expertise is urgently in demand right now.", author:"Claude" },
]

export const TIPS = [
  "Apply on Monday or Tuesday morning — hiring managers review applications at the start of the week.",
  "Personalise the first 2 lines of every cover letter. It takes 3 minutes and doubles callback rate.",
  "Follow up by email 5 days after applying. Most candidates never do this. It sets you apart.",
  "Connect with the hiring manager on LinkedIn BEFORE applying. It puts your name in their head.",
  "Register with at least 3 recruitment agencies. 80% of Dublin tech roles go through agencies first.",
  "Set up job alerts on LinkedIn AND Indeed AND IrishJobs — new roles post at different times on each.",
  "Add 'Immediately available' and 'Open to contract and permanent' to your LinkedIn headline right now.",
  "Your LLM evaluation experience at Meta is your biggest USP. Lead with it in every application.",
  "For T&S roles, mention GDPR, DSA, and EU AI Act in your CV — these are ATS filter keywords.",
  "Apply to 5-10 roles per week minimum. Job searching is a numbers game as well as a quality game.",
]

export const SV_NEWS = [
  { title:"Anthropic hits $30B revenue in April 2026 — in early IPO talks with Goldman Sachs", url:"https://venturebeat.com/category/ai", source:"VentureBeat", date:"Apr 25, 2026", tag:"AI", relevance:"Anthropic Dublin is hiring — major growth signal" },
  { title:"Google invests up to $40B in Anthropic at ~$350B valuation", url:"https://techcrunch.com/category/artificial-intelligence/", source:"TechCrunch", date:"Apr 25, 2026", tag:"Funding", relevance:"Google and Anthropic Dublin partnerships expanding" },
  { title:"Meta confirms 8,000 layoffs but doubles AI capex to $115–135B in 2026", url:"https://techcrunch.com/category/artificial-intelligence/", source:"TechCrunch", date:"Apr 25, 2026", tag:"AI", relevance:"Meta Dublin T&S team unaffected — capex shows AI commitment" },
  { title:"EU AI Act full enforcement starts August 2, 2026 — 99 days away", url:"https://artificialintelligenceact.eu/", source:"EU AI Act", date:"Apr 25, 2026", tag:"Policy", relevance:"Your EU AI Act knowledge is urgently in demand RIGHT NOW" },
  { title:"Microsoft launches 3 new foundational AI models: MAI-Transcribe, MAI-Voice, MAI-Image", url:"https://techcrunch.com/2026/04/02/microsoft-takes-on-ai-rivals-with-three-new-foundational-models/", source:"TechCrunch", date:"Apr 3, 2026", tag:"AI", relevance:"Microsoft Dublin expanding AI teams" },
  { title:"OpenAI proposes public wealth funds and robot taxes as AI reshapes jobs", url:"https://techcrunch.com/2026/04/06/openais-vision-for-the-ai-economy-public-wealth-funds-robot-taxes-and-a-four-day-work-week/", source:"TechCrunch", date:"Apr 6, 2026", tag:"Policy", relevance:"T&S and AI governance roles growing in strategic importance" },
  { title:"DeepSeek releases V4-Pro open-source — 1.6T parameters, one-sixth cost of GPT-5.5", url:"https://venturebeat.com/category/ai", source:"VentureBeat", date:"Apr 24, 2026", tag:"AI", relevance:"Open-source AI boom = more LLM evaluation roles" },
  { title:"Silicon Valley confronts AI job panic — companies cite AI in announcing cuts", url:"https://techxplore.com/news/2026-04-hiring-humans-silicon-valley-ai.html", source:"TechXplore", date:"Apr 12, 2026", tag:"Jobs", relevance:"T&S and policy roles are protected — AI needs human oversight" },
  { title:"Google deepens Thinking Machines Lab ties with new multibillion-dollar deal", url:"https://techcrunch.com/2026/04/22/exclusive-google-deepens-thinking-machines-lab-ties-with-new-multi-billion-dollar-deal/", source:"TechCrunch", date:"Apr 22, 2026", tag:"AI", relevance:"Google AI expanding — Dublin office benefits" },
  { title:"AI demand for ML engineers nearly doubled since 2023 — ManpowerGroup data", url:"https://leaddev.com/hiring/how-ai-boom-bringing-silicon-valley-back-brink", source:"LeadDev", date:"2026", tag:"Jobs", relevance:"Your LLM evaluation skills are at peak demand globally" },
]
